### ISSUE TITLE
User guide to deploy paradrop controller in my server

### ISSUE THREAD

**Issue by WormOn** [ParadropLabs/Paradrop#15]
I want to have a user  guide to deploy paradrop controller in my server.

**Comment by lhartung** [comment]
By controller, I think you are referring to the configuration and management server that we operate at paradrop.org, as described in our [System Architecture](http://paradrop.readthedocs.io/en/latest/architecture/index.html) document. For most applications that people build with Paradrop, we have found no need to run a separate instance of the controller software. Consequently, we have not released a public version of the controller software. If you would like to tell us more about your application or use case, we can try to help you out.

**Comment by WormOn** [comment]
Now I have school programe that need to deploy a private paradrop controller.Because the network which the programme use is isolated from Public Internet.So I hope that you and your team can share the related document to me.Thank you very much.

**Comment by lhartung** [comment]
I see. Since you have an isolated network setup, you can run the Paradrop nodes standalone, without a connection to the controller. Although I am not familiar with your project, I would guess the functionality you will need should be available through the edge node API. For example, our [Python tutorial](http://paradrop.readthedocs.io/en/latest/application/getting-started-python.html), uses the pdtools command and the IP address of the compute node to install a chute on the node without interacting with the controller. This standalone operation is very useful in many situations, so it is something we will continue to support. Unfortunately, we are not able to support running a private controller at this time.

**Comment by lhartung** [comment]
I am sorry for your disappointment. I would still encourage you to try running your project with the edge compute node in a standalone configuration. You will not need to do any extra work to enable that. If you set up a Paradrop node and do not link it to the cloud controller, it will function on its own as a compute node with full networking capabilities. Paradrop also supports running behind a NAT, if that was your original concern. If you are approaching this from a background with enterprise WiFi APs and their controllers, Paradrop does things a little differently from what you might expect. Paradrop generally does not send data traffic through our cloud controller.
